Signup page
codersforcauses/foodbank pull request #107
Opened 2021-01-09 07:05 UTC by bronsenivulich

Created the component and storybook file for login and signup form.  Also started yup validation.

2021-01-11 18:23 UTC, neosh11 commented on client/.eslintrc.json
> +    "plugin:@typescript-eslint/recommended",
is there any diff between 16/19

2021-01-15 02:54 UTC, benjaminpodmore commented on client/.eslintrc.json
> +    "plugin:@typescript-eslint/recommended",
no, fixed thanks <3

2021-01-18 15:02 UTC, bronsenivulich commented
I didn't mean to merge the two branches, will fix asap

2021-01-19 02:24 UTC, benjaminpodmore commented
> 
> 
> I didn't mean to merge the two branches, will fix asap

junk

2021-01-20 08:51 UTC, JeremiahPinto requested changes
Most of this seems good, but there isn't a link in the forms to easily switch between login and signup. Here is an example of how GitHub does it:

![Screen Shot 2021-01-20 at 4 50 11 pm](https://user-images.githubusercontent.com/24516879/105150420-b6085a00-5b3f-11eb-8715-70cd12eb8469.png)

2021-01-20 08:51 UTC, JeremiahPinto commented on client/.eslintrc.json
> +    "plugin:@typescript-eslint/recommended",
why is this still there?

2021-01-20 08:51 UTC, JeremiahPinto commented on client/src/Components/Forms/User/index.tsx
> +    .min(1, 'Username must be at least 1 character')
This is unnecessary as the required field would fit the requirements of the min length

2021-01-20 08:51 UTC, JeremiahPinto commented on client/src/Pages/Login/index.css
> +}
Please use the tailwind classes rather than your own css file

2021-01-20 08:51 UTC, JeremiahPinto commented on client/src/Pages/SignUp/index.css
> +}
Same with this file regarding css

2021-02-03 10:06 UTC, JeremiahPinto approved these changes

2021-02-03 10:06 UTC, merged