S174 trophy room frontend
codersforcauses/foodbank pull request #213
Opened 2022-01-22 06:26 UTC by chenga3

![image](https://user-images.githubusercontent.com/39249792/150627067-19738375-092e-4d1e-a4b2-44c6ed1dc372.png)

Implemented frontend for trophy room page. Correct number of trophies render based on a hard-coded variable.

Still to do (front end):
- Add responsiveness
- Add popover for trophy info (name, description) which renders on hover

2022-01-27 09:42 UTC, CodeWithTheDoctor commented on components/TrophyRoom/TrophyCabinet/index.tsx
> +import TrophyCabinetImage from 'public/images/trophy-cabinet.png'
Trophy cabinet should also be .webp no?

2022-01-29 00:51 UTC, chenga3 commented on components/TrophyRoom/TrophyCabinet/index.tsx
> +import TrophyCabinetImage from 'public/images/trophy-cabinet.png'
donezo

2022-02-13 03:48 UTC, CodeWithTheDoctor commented
Need to set the `Trophy Room` button in the navbar to send us to the trophy-room page

2022-02-13 03:50 UTC, CodeWithTheDoctor commented
Noticed some styling issue we need to fix
![image](https://user-images.githubusercontent.com/22740095/153737822-2711bdbd-aff7-4389-ad66-4a975efa3a4b.png)

Should be a lil tweaking needed in the classes added. I might work on fixing those

2022-02-13 03:59 UTC, CodeWithTheDoctor requested changes
Just need to fix bit of styling and It's good to be merged then

2022-02-13 04:15 UTC, CodeWithTheDoctor approved these changes

2022-02-13 04:16 UTC, merged