Completed recipes page #23
codersforcauses/foodbank pull request #224
Opened 2022-02-03 17:16 UTC by APM246

## Change Summary
Completed recipes section of website, including:
- grid of recipes
- overview page for each recipe
- Slideshow modal
- All-steps page
- Download PDF button

 Closes a number of issues including #23, #54 and #197

## Other Information
Has been tested on all devices including mobile and tablets.

2022-02-05 03:17 UTC, CodeWithTheDoctor commented
Not an urgent issue, but the "Let's cook" section has a visible scroll bar, 
I think removing it might be good, using the css down remove...

Also, it might be worth creating a custom, purple-coloured scrollbar... anyway, not super related to the issue and isn't really a big problem. I'm still in the process of reviewing the code.
```
/* Hide scrollbar for Chrome, Safari and Opera */
.no-scrollbar::-webkit-scrollbar {
    display: none;
}

/* Hide scrollbar for IE, Edge and Firefox */
.no-scrollbar {
    -ms-overflow-style: none;  /* IE and Edge */
    scrollbar-width: none;  /* Firefox */
}
```

2022-02-07 05:30 UTC, CodeWithTheDoctor commented
![image](https://user-images.githubusercontent.com/22740095/152729658-5f1a351c-0a0b-40c5-be9f-5df34a09a897.png)

I'm not sure if it is meant to look like this ahah... 😅

2022-02-10 05:39 UTC, CodeWithTheDoctor requested changes
The images also need to be in .webp format and need to be compressed using a tool such as https://squoosh.app/ as mentioned by Jeremiah on last Saturday.

2022-02-12 04:27 UTC, innoc3ntt commented on components/Recipe/Overview/index.tsx
> +    const fullConfig = resolveConfig(tailwindConfig)
removed!

2022-02-12 04:28 UTC, innoc3ntt commented on lib/types.ts
> +//TODO: Fix the API to return ColorScheme as a required parameter. Just random values atm
been fixed

2022-02-12 05:26 UTC, APM246 commented
Not all recipes have their PDFs added to the repo (so download PDF button doesn't work for them)

2022-02-19 06:13 UTC, chenga3 submitted a review, later dismissed

2022-02-19 06:33 UTC, merged