Adds navbar toggle button
codersforcauses/foodbank pull request #67
Opened 2020-12-12 07:52 UTC by bronsenivulich

2020-12-12 08:04 UTC, tim-ings approved these changes

2020-12-12 18:22 UTC, JeremiahPinto requested changes
I understand this may be early, but it's good so you can get feedback early

2020-12-12 18:22 UTC, JeremiahPinto commented on client/src/App/index.tsx
> +import { Navbar } from '../Components/Navbar'
I've set up a config so you can just use `Components/Navbar`

2020-12-12 18:22 UTC, JeremiahPinto commented on client/src/App/index.tsx
>        <header>foodbank</header>
delete this line

2020-12-12 18:22 UTC, JeremiahPinto commented on client/src/Components/Navbar/index.tsx
> +import './navbar.css';
Please use the [tailwindcss](https://tailwindcss.com/docs/display) classes.

2020-12-12 18:22 UTC, JeremiahPinto commented on client/src/Components/Navbar/index.tsx
> +    <div>
Use `header` here. Try to stick with semantic HTML where possible

2020-12-12 18:22 UTC, JeremiahPinto commented on client/src/Components/Navbar/navbar.css
> +}
This file can be deleted when tailwind is used

2020-12-13 13:33 UTC, JeremiahPinto commented
I am definitely confused, is this Tim or Bronsen working on it.

2020-12-13 15:10 UTC, Drewbi commented
> I am definitely confused, is this Tim or Bronsen working on it.

Team effort 😆

2020-12-13 15:51 UTC, tim-ings commented
We paired on Saturday, figured I'd fix the remaining issues here so this can be merged and Bronsen is free to get started on the next part of his ticket.

2020-12-16 06:13 UTC, JeremiahPinto approved these changes

2020-12-16 06:13 UTC, merged