Niall/button
codersforcauses/foodbank pull request #78
Opened 2020-12-14 12:58 UTC by niallCDS

Storybook highlights issues of insufficient colour contrast for accessibility purposes with the orange, blue and teal buttons with the white text. Should we be considering adding more contrast to colours?

I believe I've completed issue #46.

2020-12-16 06:34 UTC, JeremiahPinto requested changes
Please rename the components to `index`. It's unnecessary to call them Button when it's inside the `Button` folder.

Also, the box-shadow doesn't show up in storybook.

> Storybook highlights issues of insufficient colour contrast for accessibility purposes with the orange, blue and teal buttons with the white text. Should we be considering adding more contrast to colours?

If you check the wiki, there should be a section under the branding guideline that talks about the contrast of the button and text. Would be great if you could incorporate that into the component but it's not critical right now.

2020-12-16 06:34 UTC, JeremiahPinto commented on client/src/Components/Button/Button.tsx
> +        'px-24',
That's a bit too much padding. should probs be around 2rem

2020-12-18 10:37 UTC, Drewbi commented
The style's looking pretty good, only thing is we either need purple button to always have white text or we need to add a prop for text colour.

2021-01-13 05:11 UTC, JeremiahPinto requested changes
Please fix as commented. Almost donw tih this component otherwise

2021-01-13 05:11 UTC, JeremiahPinto commented on client/src/Components/Button/index.tsx
>    label: string
Instead of label, use react `children` prop

2021-01-13 05:11 UTC, JeremiahPinto commented on client/src/Components/Button/index.tsx
> +        `bg-${backgroundColour}`,
tailwind does not work when using string templates as such. Have a look at how I did the textfield component when a prop has a conditional

2021-01-13 05:11 UTC, JeremiahPinto commented on client/src/Components/Button/index.tsx
> +        'uppercase'
these can be merged into one string

2021-01-13 05:11 UTC, JeremiahPinto commented on client/src/Components/Button/index.tsx
>  export const Button: React.FC<ButtonProps> = ({
export default rather than export const

2021-01-13 05:11 UTC, JeremiahPinto commented on client/src/stories/Header.tsx
> +import { Button } from 'Components/Button/index'
You don't need to declare index. It would just be `Components/Button`

2021-01-13 05:11 UTC, JeremiahPinto commented on client/src/Components/Button/index.stories.tsx
> +import { Button, ButtonProps } from './index'
This would be `from '.'`

2021-01-15 06:24 UTC, Drewbi submitted a review, later dismissed

2021-01-15 06:27 UTC, Drewbi commented on client/src/Components/Button/index.tsx
>  export const Button: React.FC<ButtonProps> = ({
`export default`

2021-01-15 06:30 UTC, Drewbi submitted a review, later dismissed
Just fix that const export and I think we're good to go :O

2021-01-15 18:23 UTC, Drewbi approved these changes

2021-01-15 18:23 UTC, merged