Bronsen/style floating button
codersforcauses/foodbank pull request #83
Opened 2020-12-17 13:52 UTC by bronsenivulich

The button has been styled and some animations have been attempted, however it's not 100% complete yet.

2020-12-20 17:15 UTC, noobling commented on client/src/Components/Branding/Fonts/index.tsx
> +  both: boolean
Enums can be useful here instead of magic strings https://softwareengineering.stackexchange.com/questions/365339/what-is-wrong-with-magic-strings

2020-12-28 10:57 UTC, Drewbi commented
I've added the WIP flag, remove it when you've pulled main into your branch and are ready for review :)

2021-01-13 05:28 UTC, JeremiahPinto requested changes
please fix your git config to use `lf` rather than the windows default. Not reviewing this until it's fixed as all future PRs with have the same issue

2021-01-15 06:01 UTC, Drewbi requested changes

2021-01-15 06:01 UTC, Drewbi commented on client/src/Components/Navbar/index.tsx
> +        <button className='sm:hidden FloatingButton' onClick={handleClick}>
To handle the rotation with tailwind id suggest something like 
```
className={`transform ${open ? 'rotate-45' ? ''}`}
```

2021-01-15 06:01 UTC, Drewbi commented on client/src/Components/Navbar/index.css
> +.FloatingButton {
There's a lot of css that can be converted into tailwind here but while you're experimenting using normal css is fine.

2021-01-15 06:01 UTC, Drewbi commented on client/src/Components/Navbar/index.css
> +  border: 2px solid #00acd0;
I don't think this border fits with their branding, i think just the rounded purple background is fine

2021-02-13 07:27 UTC, JeremiahPinto requested changes
There's a lot of stuff that needs to be fixed here. I guess this PR is old but it should be easier to update now that you have a bit more experience working with react since you initially built the feature.

2021-02-13 07:27 UTC, JeremiahPinto commented on client/src/Components/Branding/Fonts/index.stories.tsx
> +import { Story, Meta } from 'react'
This isn't imported from react, its a storybook component. Same with all other imports below

2021-02-13 07:27 UTC, JeremiahPinto commented on client/src/Components/FloatingButton/index.tsx
> +import './index.css'
Pretty much all the css you have here can be built using the tailwind classes

2021-02-13 07:27 UTC, JeremiahPinto commented on client/src/Components/FloatingButton/index.tsx
> +  }
Why is vanilla js used here when the state change can be done directly using react.

2021-02-20 07:06 UTC, tim-ings commented on client/src/Components/FloatingButton/index.tsx
> +  return windowWidth > 640 ? null : <FloatingButton />
Logic based on the window width/height should be done in css. Tailwind has some [helper classes](https://tailwindcss.com/docs/breakpoints) for different screen size breakpoints.

2021-02-20 07:06 UTC, tim-ings commented on client/src/Components/FloatingButton/index.css
> +/* /* .FloatingButton {
There's no need for this file

2021-07-11 21:01 UTC, closed without merging